plugins
{
	id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}

repositories
{
	maven { url = "https://repo.spongepowered.org/repository/maven-public" }
}

dependencies
{
	minecraft "com.mojang:minecraft:${minecraft_version}"

	compileOnly "org.spongepowered:mixin:0.8.5:processor"

	testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.test
{
	useJUnitPlatform()
}

loom
{
	mixin.useLegacyMixinAp = false
}
