plugins
{
	id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

dependencies
{
	testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	testImplementation "net.neoforged:testframework:${neoforge_version}"
}

neoForge
{
	version = neoforge_version

	runs
	{
		client { client() }
		server { server() }
	}

 	mods
	{
		"${mod_id}" { sourceSet sourceSets.main }
	}

	unitTest
	{
		enable()
		testedMod = mods.mocap
	}
}


tasks.test
{
	useJUnitPlatform()
}
